# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 14:05
from __future__ import unicode_literals
from django.db import migrations


def create_stuff(apps, schema_editor):
    data = (
        ('Monkey junk', 'this is how you fight demons before you cant'),
        ('Cow Fighter', 'Fancy things make short things stronger'),
        ('Castor Boiled Crawfish', 'No, stop breathing. you are already dead')
    )

    Example = apps.get_model('app.Example')
    Example.objects.bulk_create(
        [Example(name=x[0], description=x[1]) for x in data])


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_stuff)
    ]
